# version: "3"
# services:
#  secops-secure:
#   build: ./
#   container_name: secops-secure
#   ports:
#    - 5001:5000
#   environment:
#    - vulnerable=0

#  secops-vulnerable:
#   build: ./
#   container_name: secops-vulnerable
#   ports:
#    - 5002:5000
#   environment:
#    - vulnerable=1


version: "3"

services:
  secops:
    image: taiwrash/secops:latest
    container_name: secops
    ports:
      - "5000:5000"
    environment:
      - vulnerable=0
    restart: unless-stopped
