name: Full CI

on:
  push:
    branches: [ "main" ]

jobs:

  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     -
  #       name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     -
  #       name: Build and push
  #       uses: docker/build-push-action@v3
  #       with:
  #         push: true
  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/vampi:latest
  #         platforms: linux/amd64,linux/arm64

  test:
    runs-on: ubuntu-latest
    steps:
      -
       name: Checkout the repo
       uses: actions/checkout@v3

      - name: Find leaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: >
            detect
            --report-format json
            --report-path gitleaks.json
        continue-on-error: true

      - name: Send Gitleaks report
        run: |
          ls -lh gitleaks.json
          curl -X POST https://be20e70905b6.ngrok-free.app/api/v1/ingest \
            -H "Authorization: Bearer almag_sk_1767868327785568000" \
            -F "tool=gitleaks" \
            -F "report=@gitleaks.json"

      

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep Scan
        run: |
          semgrep --config p/ci --error


      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: docker.io/taiwrash/trigra:latest
          format: json
          output: trivy.json
        continue-on-error: true

      - name: Send Trivy report
        run: |
          ls -lh trivy.json
          curl -X POST https://be20e70905b6.ngrok-free.app/api/v1/ingest \
            -H "Authorization: Bearer almag_sk_1767868327785568000" \
            -F "tool=trivy" \
            -F "report=@trivy.json"